# Generated by Django 2.0.7 on 2018-07-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0003_auto_20180731_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibration',
            name='date_expired',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='date_issued',
            field=models.DateField(blank=True, null=True),
        ),
    ]
