# Generated by Django 2.0.7 on 2018-08-26 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0006_profile_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userType',
            field=models.CharField(blank=True, choices=[('regular_admin', 'Admin'), ('super_admin', 'Super Admin')], max_length=50, null=True),
        ),
    ]
